[package]
name = "btrfs-diskformat"
version = "0.1.0"
authors = ["Christopher Tam <ohgodtamit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
static_assertions = "1.1.0"
zerocopy = "0.2.8"
